language: node_js
notifications:
  email: false
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  provider: npm
  email: $EMAIL
  api_key:
    secure: Xvg7Hk5ZqLn50VLVXm6RvIFm0fA9Y3AUIZmpg1weOLgygjOsZWjfngGXy7/rQ5KRz0phU06XOoAe/3Iv1eJ44+VnXBLZ4nhaiHlSGBy0QQltq85K5jjvIOcIX1SiKMuqJjLWQe59lvkDFiKPPpc5C/ErSJ2kM4yhXNB0VvFCgjOTo3x6+3AW+qoAFrS0TjDbkzMfdDLwlpk4d7ygvjgGpHsvf6GB1EtVxRW70Jo/Pu9hfccb061RVULo2sW9DzNv4iEUQsfDPG+0/vQZ3YIyHvzQnVjzLRNrAMG2nnmcq0eUjS3STZ9gLYlJJKfVADO1abOngsfDjggJwAli9y+mdLcXKInpvS6rH3T91MZX8GGsBrUWzXG3rspJAileiERFB/6SJpB0JA6Gy0PVP73y7RnKyhJ1TEXtD2QSm4NSSTOp0L60acupW8jScIfgu8M2jk2lCK0zF7Cq6YjlnBbx96GRft0OZ67mk2hlaXR14s9vidy5sEwIp668UphbaxTlV3jIG/CfDcpPkEip/Jy7JobRxFuXE/BgvCOsYm7HU/5RhmgNHRn2k14UqiqVu6xwyJO31SQG9+FZFY10L7ud9zhi2LDY7SQG0CDA6adLVWJRatiGtgzmJZYsYEJgsUGcVZry5/6sc5U89FU3MSFbXw6FeVLS6npouF0m9BhfdU0=
  on:
    tags: true
    repo: domjtalbot/sassdoc-loader
